from enum import StrEnum


class TaskMode(StrEnum):
    NEW_GENERATION = "NEW_GENERATION"
    EXISTING_IMAGE_EDIT = "EXISTING_IMAGE_EDIT"
    STRICT_PRESERVATION_EDIT = "STRICT_PRESERVATION_EDIT"
    SELECTIVE_EDIT = "SELECTIVE_EDIT"
    CREATIVE_REGENERATION = "CREATIVE_REGENERATION"
    RETOUCH_ONLY = "RETOUCH_ONLY"
    RELIGHT = "RELIGHT"
    COLOR_GRADE = "COLOR_GRADE"
    LUT_LOOK_APPLICATION = "LUT_LOOK_APPLICATION"
    SOURCE_WEBSITE_TREATMENT = "SOURCE_WEBSITE_TREATMENT"
    REFERENCE_RESEARCH = "REFERENCE_RESEARCH"
    PRODUCT_IMAGE = "PRODUCT_IMAGE"
    PORTRAIT = "PORTRAIT"
    FASHION_EDITORIAL = "FASHION_EDITORIAL"
    LIFESTYLE_DOCUMENTARY = "LIFESTYLE_DOCUMENTARY"
    CINEMATIC_STILL = "CINEMATIC_STILL"
    MOBILE_SOCIAL_REALISM = "MOBILE_SOCIAL_REALISM"


class PublicJobStatus(StrEnum):
    QUEUED = "queued"
    WORKING = "working"
    READY = "ready"
    NEEDS_REVIEW = "needs_review"
    BLOCKED = "blocked"
    FAILED = "failed"
